from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_self(object):
    def setupUi(self):
        self.resize(805, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.search_tab = QtWidgets.QWidget()
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.frame = QtWidgets.QFrame(self.search_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, -1, 9, -1)
        self.search_query_textbox = QtWidgets.QTextEdit(self.frame)
        self.search_query_textbox.setMinimumSize(QtCore.QSize(0, 34))
        self.search_query_textbox.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.search_query_textbox.setFont(font)
        self.horizontalLayout.addWidget(self.search_query_textbox)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(175, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setMinimumSize(QtCore.QSize(0, 34))
        self.horizontalLayout.addWidget(self.search_button)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(self.search_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 781, 312))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.search_tab, "")
        self.tracking_tab = QtWidgets.QWidget()
        self.tabWidget.addTab(self.tracking_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.console_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.console_log.setEnabled(True)
        self.console_log.setMaximumSize(QtCore.QSize(16777215, 200))
        self.console_log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.console_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.console_log.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.console_log.setReadOnly(True)
        self.console_log.setPlainText("")
        self.console_log.setBackgroundVisible(False)
        self.console_log.setCenterOnScroll(True)
        self.console_log.setPlaceholderText("")
        self.verticalLayout.addWidget(self.console_log)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.verticalLayout.addWidget(self.progressBar)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 22))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(self)
        self.actionShow_Logs = QtWidgets.QAction(self)
        self.actionShow_Logs.setCheckable(True)
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionShow_Logs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.tabWidget.setCurrentIndex(0)

        self.setWindowTitle("Product $ Tracker")
        self.search_query_textbox.setPlaceholderText("Enter Product URL or Search Query")
        self.comboBox.setItemText(0, "Relevance")
        self.comboBox.setItemText(1, "Price: High to Low")
        self.comboBox.setItemText(2, "Price: Low to High")
        self.search_button.setText("Search")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_tab), "Search")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tracking_tab), "Tracking")
        self.menuFile.setTitle("File")
        self.menuSettings.setTitle("Settings")
        self.menuAbout.setTitle("About")
        self.actionQuit.setText("Quit")
        self.actionShow_Logs.setText("Show Logs")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    self = QtWidgets.Qself()
    ui = Ui_self()
    ui.setupUi(self)
    self.show()
    sys.exit(app.exec_())
