from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *
import requests

from func import trim_name


class ResultCard(QWidget):
    def __init__(self, product):
        super().__init__()
        self.showUI(product)

    def setupUi(self, product):
        self.resize(720, 218)
        self.horizontalLayout = QHBoxLayout(self)

        self.picture = QLabel(self)
        self.picture.setMinimumSize(QtCore.QSize(128, 128))
        self.picture.setMaximumSize(QtCore.QSize(175, 200))
        self.picture.setText("")
        self.horizontalLayout.addWidget(self.picture)

        self.main_frame = QFrame(self)
        self.main_frame.setFrameShape(QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.main_frame)

        self.product_title_2 = QLabel(self.main_frame)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.product_title_2.setFont(font)
        self.verticalLayout_2.addWidget(self.product_title_2)
        self.source_label_2 = QLabel(self.main_frame)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_label_2.sizePolicy().hasHeightForWidth())
        self.source_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.source_label_2.setFont(font)
        self.verticalLayout_2.addWidget(self.source_label_2)
        self.label_4 = QLabel(self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(202, 202, 202);")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_5 = QLabel(self.main_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_3 = QLabel(self.main_frame)
        self.verticalLayout_2.addWidget(self.label_3)
        self.track_button_2 = QPushButton(self.main_frame)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_button_2.sizePolicy().hasHeightForWidth())
        self.track_button_2.setSizePolicy(sizePolicy)
        self.track_button_2.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.track_button_2.setFont(font)
        self.verticalLayout_2.addWidget(self.track_button_2)
        self.horizontalLayout.addWidget(self.main_frame)

        self.product_title_2.setText("Lorem Ipsum Product")
        self.source_label_2.setText("Fetched from Amazon.com")
        self.label_4.setText("ID: B9we8frw9")
        self.label_5.setText("CURRENTLY: INR 450")
        self.label_3.setText("Max: Mix: Avg: ")
        self.track_button_2.setText("View Price History")